# Generated by Django 4.1.7 on 2023-03-08 06:40

import adventure.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('amount_players', models.IntegerField(validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)], verbose_name='Количество игроков')),
                ('duration', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)], verbose_name='Примерная длительность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, default='adventure/default/default_img.png', null=True, upload_to=adventure.models.user_directory_path, verbose_name='Изображение')),
                ('file', models.FileField(upload_to=adventure.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['rar', 'zip', 'json'])], verbose_name='Файл')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Отредактирован')),
                ('user', models.ForeignKey(default='Комьюнити', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Приключение',
                'verbose_name_plural': 'Приключения',
                'ordering': ['time_update'],
            },
        ),
    ]
