# Generated by Django 4.1.7 on 2023-03-08 06:59

import adventure.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='image',
            field=models.ImageField(blank=True, default='adventure/default/default_img_test.png', null=True, upload_to=adventure.models.user_directory_path, verbose_name='Изображение'),
        ),
    ]
